In [8]:
import pandas as pd 
import sys
import h5py
import numpy as np
import tables as HDF5

In [9]:
import glob
files = glob.glob('/content/drive/MyDrive/MillionSongSubset/*/*/*/*.h5')

In [10]:
len(files)

10000

In [11]:
filter(lambda x: x[:3] == 'get',HDF5.__dict__.keys())

In [13]:
%time
artist_names = []
artist_familiarity = []
artist_hotttnesss = []
artist_id = []
artist_latitude = []
artist_longitude = []
artist_location = []
song_id = []

for f in files:
    
    h5 = h5py.File(f, 'r')
    
    artist_name = h5['metadata']['songs']['artist_name'][0].decode('utf-8')
    artist_familiar = h5['metadata']['songs']['artist_familiarity'][0]
    artist_hot = h5['metadata']['songs']['artist_hotttnesss'][0]
    artist_ids = h5['metadata']['songs']['artist_id'][0]
    artist_lat = h5['metadata']['songs']['artist_latitude'][0]
    artist_long = h5['metadata']['songs']['artist_longitude'][0]
    artist_loc = h5['metadata']['songs']['artist_location'][0].decode('utf-8')
    song_idss = h5['metadata']['songs']['song_id'][0].decode('utf-8')
    
    artist_names.append(artist_name)
    artist_familiarity.append(artist_familiar)
    artist_hotttnesss.append(artist_hot)
    artist_id.append(artist_ids)
    artist_latitude.append(artist_lat)
    artist_longitude.append(artist_long)
    artist_location.append(artist_loc)
    song_id.append(song_idss)
    
    h5.close()

CPU times: user 8 µs, sys: 1e+03 ns, total: 9 µs
Wall time: 12.9 µs

In [14]:
data_artist = {'song_id':song_id
        ,'artist_names':artist_names
        ,'artist_familiarty':artist_familiarity
        ,'artist_hotness':artist_hotttnesss
        ,'artist_latitude':artist_latitude
        ,'artist_longitude':artist_longitude
        ,'artist_location':artist_location
        ,'artist_id':artist_id
       }

In [15]:
artist_df=pd.DataFrame(data_artist)

In [16]:
len(artist_df)

10000

In [17]:
artist_df.head()

,song_id,artist_names,artist_familiarty,artist_hotness,artist_latitude,artist_longitude,artist_location,artist_id
0,SOBQAPA12A8C13261C,Basement Jaxx,0.803619,0.531213,NaN,NaN,"London, England",b'ARFSPOV1187B9B2363'
1,SOYIWNY12AC3DF96FC,Lady Saw,0.680620,0.440326,NaN,NaN,"St. Mary's, Jamaica",b'ART5IUL1187B9B0143'
2,SOAMUDI12A6D4FCD11,Coco Montoya,0.576452,0.420007,34.01156,-118.49229,"Santa Monica, CA",b'ARKBCZ91187B98F486'
3,SOHKQXL12A8C1379B9,Virtue,0.564594,0.310069,NaN,NaN,,b'ARO3PIY1187B989933'
4,SOCYJTH12AB0184649,Franco,0.600487,0.453270,NaN,NaN,"Sona-Bata, Zaire",b'ARPHH7Z1187B9B6A3A'

In [18]:
song_id = []
song_titles =[]
song_durations =[]
song_release_years =[]
song_hotness  =[]
track_id =[]
%time
for f in files:
    
    h5 = h5py.File(f, 'r')
    
    song_idss = h5['metadata']['songs']['song_id'][0].decode('utf-8')
    song_title = h5['metadata']['songs']['title'][0]
    song_duration = h5['analysis']['songs']['duration'][0]
    song_release_year = h5['musicbrainz']['songs']['year'][0]
    song_hot = h5['metadata']['songs']['song_hotttnesss'][0]
    track_idss = h5['analysis']['songs']['track_id'][0]
    
    song_id.append(song_idss)
    song_titles.append(song_title)
    song_durations.append(song_duration)
    song_release_years.append(song_release_year)
    song_hotness.append(song_hot)
    track_id.append(track_idss)
    
    h5.close()

CPU times: user 14 µs, sys: 1e+03 ns, total: 15 µs
Wall time: 20.5 µs

In [19]:
data_song = {'song_id':song_id
        ,'track_id':track_id
        ,'song_titles':song_titles
        ,'song_durations':song_durations
        ,'song_release_years':song_release_year
        ,'song_hotness':song_hotness
       }

In [20]:
song_df=pd.DataFrame(data_song)

In [21]:
len(song_df)

10000

In [22]:
song_df.head()

,song_id,track_id,song_titles,song_durations,song_release_years,song_hotness
0,SOBQAPA12A8C13261C,b'TRASIKP128F423EED7',b'La Photo',240.01261,2007,0.360371
1,SOYIWNY12AC3DF96FC,b'TRASIWA12903CFFC4D',b'Get A Straw',207.12444,2007,0.215080
2,SOAMUDI12A6D4FCD11,b'TRASIWH128F4234005',b'Gotta Mind To Travel',233.48200,2007,NaN
3,SOHKQXL12A8C1379B9,b'TRASIDP128F428ECD1',b'Can You Hear The Angels',223.05914,2007,0.000000
4,SOCYJTH12AB0184649,b'TRASITK128F92F346F',b'Die T\xc3\xbcr die zum Gl\xc3\xbcck f\xc3\xb...,220.47302,2007,0.000000

In [23]:
song_tempo = []
song_bars =[]
song_beats = []
song_time_signatures =[]
song_tatum =[]
song_modes=[]
song_keys=[]
song_id = []

%time
for f in files:
    
    h5 = h5py.File(f, 'r')
    
    song_speed = h5['analysis']['songs']['tempo'][0]
    song_bar = h5['analysis']['bars_start'][()]
    song_beat = h5['analysis']['beats_start'][()]
    song_time_signature = h5['analysis']['songs']['time_signature'][0]
    song_tat = h5['analysis']['tatums_start'][()]
    song_mode = h5['analysis']['songs']['mode'][0]
    song_key = h5['analysis']['songs']['key'][0]
    song_idss = h5['metadata']['songs']['song_id'][0].decode('utf-8')
    
    song_tempo.append(song_speed)
    song_bars.append(song_bar)
    song_beats.append(song_beat)
    song_time_signatures.append(song_time_signature)
    song_tatum.append(song_tat)
    song_modes.append(song_mode)
    song_keys.append(song_key)
    song_id.append(song_idss)
    
    h5.close()

CPU times: user 8 µs, sys: 1 µs, total: 9 µs
Wall time: 11.7 µs

In [24]:
data_song_more = {'song_id':song_id
        ,'song_tempo':song_tempo
        ,'song_bars':song_bars
        ,'song_beats':song_beats
        ,'song_time_signatures':song_time_signatures
        ,'song_tatum':song_tatum
        ,'song_modes':song_modes
        ,'song_keys':song_keys
       }

In [25]:
song_more_df=pd.DataFrame(data_song_more)

In [26]:
len(song_more_df)

10000

In [27]:
song_more_df.head()

,song_id,song_tempo,song_bars,song_beats,song_time_signatures,song_tatum,song_modes,song_keys
0,SOBQAPA12A8C13261C,Basement Jaxx,"[2.52412, 3.95827, 5.25168, 6.59976, 8.0155, 9...",228.299,3,"[1.81179, 2.05319, 2.29221, 2.52412, 2.75603, ...",0,11
1,SOYIWNY12AC3DF96FC,Lady Saw,"[1.65671, 4.11006, 6.69233, 9.44815, 12.23802,...",199.843,4,"[0.26613, 0.54333, 0.82619, 1.10303, 1.37987, ...",1,7
2,SOAMUDI12A6D4FCD11,Coco Montoya,"[0.51477, 2.06156, 3.65212, 5.19319, 6.73425, ...",226.888,4,"[0.13818, 0.51477, 0.89328, 1.27179, 1.65993, ...",0,2
3,SOHKQXL12A8C1379B9,Virtue,"[0.68725, 2.12971, 3.577, 5.02716, 6.50272, 7....",208.863,4,"[0.14536, 0.32569, 0.50602, 0.68725, 0.86578, ...",1,0
4,SOCYJTH12AB0184649,Franco,"[0.755, 2.63233, 4.53314, 6.43356, 8.32338, 10...",220.473,4,"[0.30824, 0.53162, 0.755, 0.97957, 1.21704, 1....",0,4

In [28]:
all_song_df = song_df.merge(song_more_df, on='song_id')

In [29]:
len(all_song_df)

10000

In [30]:
all_song_df.head()

,song_id,track_id,song_titles,song_durations,song_release_years,song_hotness,song_tempo,song_bars,song_beats,song_time_signatures,song_tatum,song_modes,song_keys
0,SOBQAPA12A8C13261C,b'TRASIKP128F423EED7',b'La Photo',240.01261,2007,0.360371,Basement Jaxx,"[2.52412, 3.95827, 5.25168, 6.59976, 8.0155, 9...",228.299,3,"[1.81179, 2.05319, 2.29221, 2.52412, 2.75603, ...",0,11
1,SOYIWNY12AC3DF96FC,b'TRASIWA12903CFFC4D',b'Get A Straw',207.12444,2007,0.215080,Lady Saw,"[1.65671, 4.11006, 6.69233, 9.44815, 12.23802,...",199.843,4,"[0.26613, 0.54333, 0.82619, 1.10303, 1.37987, ...",1,7
2,SOAMUDI12A6D4FCD11,b'TRASIWH128F4234005',b'Gotta Mind To Travel',233.48200,2007,NaN,Coco Montoya,"[0.51477, 2.06156, 3.65212, 5.19319, 6.73425, ...",226.888,4,"[0.13818, 0.51477, 0.89328, 1.27179, 1.65993, ...",0,2
3,SOHKQXL12A8C1379B9,b'TRASIDP128F428ECD1',b'Can You Hear The Angels',223.05914,2007,0.000000,Virtue,"[0.68725, 2.12971, 3.577, 5.02716, 6.50272, 7....",208.863,4,"[0.14536, 0.32569, 0.50602, 0.68725, 0.86578, ...",1,0
4,SOCYJTH12AB0184649,b'TRASITK128F92F346F',b'Die T\xc3\xbcr die zum Gl\xc3\xbcck f\xc3\xb...,220.47302,2007,0.000000,Franco,"[0.755, 2.63233, 4.53314, 6.43356, 8.32338, 10...",220.473,4,"[0.30824, 0.53162, 0.755, 0.97957, 1.21704, 1....",0,4

In [31]:
data = artist_df.merge(all_song_df, on='song_id')

In [32]:
len(data)

10000

In [33]:
data.head()

,song_id,artist_names,artist_familiarty,artist_hotness,artist_latitude,artist_longitude,artist_location,artist_id,track_id,song_titles,song_durations,song_release_years,song_hotness,song_tempo,song_bars,song_beats,song_time_signatures,song_tatum,song_modes,song_keys
0,SOBQAPA12A8C13261C,Basement Jaxx,0.803619,0.531213,NaN,NaN,"London, England",b'ARFSPOV1187B9B2363',b'TRASIKP128F423EED7',b'La Photo',240.01261,2007,0.360371,Basement Jaxx,"[2.52412, 3.95827, 5.25168, 6.59976, 8.0155, 9...",228.299,3,"[1.81179, 2.05319, 2.29221, 2.52412, 2.75603, ...",0,11
1,SOYIWNY12AC3DF96FC,Lady Saw,0.680620,0.440326,NaN,NaN,"St. Mary's, Jamaica",b'ART5IUL1187B9B0143',b'TRASIWA12903CFFC4D',b'Get A Straw',207.12444,2007,0.215080,Lady Saw,"[1.65671, 4.11006, 6.69233, 9.44815, 12.23802,...",199.843,4,"[0.26613, 0.54333, 0.82619, 1.10303, 1.37987, ...",1,7
2,SOAMUDI12A6D4FCD11,Coco Montoya,0.576452,0.420007,34.01156,-118.49229,"Santa Monica, CA",b'ARKBCZ91187B98F486',b'TRASIWH128F4234005',b'Gotta Mind To Travel',233.48200,2007,NaN,Coco Montoya,"[0.51477, 2.06156, 3.65212, 5.19319, 6.73425, ...",226.888,4,"[0.13818, 0.51477, 0.89328, 1.27179, 1.65993, ...",0,2
3,SOHKQXL12A8C1379B9,Virtue,0.564594,0.310069,NaN,NaN,,b'ARO3PIY1187B989933',b'TRASIDP128F428ECD1',b'Can You Hear The Angels',223.05914,2007,0.000000,Virtue,"[0.68725, 2.12971, 3.577, 5.02716, 6.50272, 7....",208.863,4,"[0.14536, 0.32569, 0.50602, 0.68725, 0.86578, ...",1,0
4,SOCYJTH12AB0184649,Franco,0.600487,0.453270,NaN,NaN,"Sona-Bata, Zaire",b'ARPHH7Z1187B9B6A3A',b'TRASITK128F92F346F',b'Die T\xc3\xbcr die zum Gl\xc3\xbcck f\xc3\xb...,220.47302,2007,0.000000,Franco,"[0.755, 2.63233, 4.53314, 6.43356, 8.32338, 10...",220.473,4,"[0.30824, 0.53162, 0.755, 0.97957, 1.21704, 1....",0,4

# New section